### ISSUE TITLE
Specify model and data in config instead of posterior

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/bayesbenchr#4]
Currently the config files are like this

```yml
- inference_engine: stan_vb
  posterior_name: "wells_centered-logistic"
  ...
```

We definitely want to keep this, but should we also be able to specify the config like this?

```yml
- inference_engine: stan_vb
  model_name: "logistic"
  dataset_name: "wells_centered"
  ...
```

Currently only the first config is possible, but there's really no technical obstacle to supporting both.
